config/routes.rb
Rails.application.routes.draw do

  delete 'items/claim', to: 'items#unclaim'
  
  resources :wishlists
  resources :items

  get 'sessions/signup'
  get 'sessions/login'
  get 'sessions/home'
  get 'sessions/logout'
  get 'sessions/user', to: 'sessions#find_user'

  get 'user/:id', to: 'items#user', as: 'claimed_items'
  get 'user/:id/json', to: 'items#userjson'

  post 'items/claim', to: 'items#claim'

  root 'sessions#signup'
    get 'login', to: "sessions#login", as: 'login'
    get 'signup', to: "sessions#signup", as: 'signup'

    get 'logout', to: "sessions#logout"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	belongs_to :wishlist
	validates :wishlist, 
		presence: true
	validates :title,
		presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :wishlists
	has_many :items

  def self.omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.image = auth.info.image
      user.token = auth.credentials.token
      user.expires_at = Time.at(auth.credentials.expires_at)
      user.save!
      user.email = auth.info.email
    end
  end
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
	belongs_to :user
	has_many :items
	validates :title,
		presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	def confirm_logged_in
  		unless session[:user_id]
  			return false
  		end
  	end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def index
    @wishlists = Wishlist.all
    @new_wishlist = Wishlist.new

  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	
	def index
		@items = Wishlist.find(params[:item][:wishlist_id]).items
    render json: @items
	end

	def create
		@item = Item.new(get_item_params)
		if @item.save
			@item.wishlist = Wishlist.find(params[:item][:wishlist_id])
    	render json: @item
		end
	end

	def update
		@item = Item.find(params[:id])
		@item.update(get_item_params)
		render json: @item
	end

	def claim
		item = Item.find(params[:item][:item_id])
		item.user = User.find(params[:item][:user_id])
		item.save
		render json: item
	end

	def unclaim
		item = Item.find(params[:item][:item_id])
		item.user = nil
		item.save
		render json: item
	end

	def index
		@items = Wishlist.find(params[:item][:wishlist_id]).items
    render json: @items
	end

	def destroy
		Item.destroy(params[:id])
		render json: "destroyed"
	end

	def user
		@user = User.find(params[:id])
	end

	def userjson
		@items = User.find(params[:id]).items
		render json: @items
	end

	private

	def get_item_params
		params.require(:item).permit(:title, :wishlist_id, :img_url, :description, :url)
	end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def signup
    if (session[:user_id] != nil) 
      redirect_to new_wishlist_path
    end
    @user = User.new
  end

  def login

  end
  
  def find_user
    user = User.find(params[:user_id])
    render json: user
  end

  def create
  	auth = env['omniauth.auth']
    user = User.omniauth(auth)
    session[:user_id] = user.id
    session[:pic] = auth.info.image
    redirect_to '/wishlists/new'
  end

  def logout
    session[:user_id] = nil
    redirect_to signup_path
  end


	private 
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController

	def index
		@user_id = session[:user_id]
	   @wishlists = Wishlist.all
	   @new_wishlist = Wishlist.new
	end

	def new
		if (session[:user_id] == nil)
			redirect_to signup_path
		else
			@user_id = session[:user_id]
			@wishlist = Wishlist.new
			@pic = session[:pic]
		end
	end

	def create
		if (session[:user_id] == nil)
			redirect_to signup_path
		else
			wish_params = wishlist_params.merge(user_id: session[:user_id])

			@wishlist = Wishlist.new(wish_params)
			if @wishlist.save
				redirect_to wishlist_path(@wishlist.id)
				@wishlist.user = User.find(session[:user_id])
			else
				redirect_to wishlists_path
			end
		end
	end

	def show
		if (session[:user_id] == nil)
			redirect_to signup_path
		else
			@user_id = session[:user_id]
			@wishlist = Wishlist.find(params[:id])
			@this_items = @wishlist.items
			# ATTEMPT TO SORT???
			# @this_items.sort_by { |i| i[:id] }
			# @this_items.each do |i|
			# 	puts "HELLOOOOO"
			# 	puts(i.id)
			# end
			@kind = @wishlist.kind
			@belongstouser = false
			if session[:user_id] == @wishlist.user_id
				@belongstouser = true
			else
				@wishlistowner = User.find(@wishlist.user_id)
				@nn_user_id = session[:user_id]
			end
		end
	end

	def edit
		@wishlist = Wishlist.find(params[:id]) 
	end

def update
	wishlist = Wishlist.find(params[:id])
	wishlist.update(wishlist_params)
	redirect_to wishlists_path
end

def destroy
	wishlist = Wishlist.find(params[:id])
	wishlist.destroy
	redirect_to wishlists_path
end

	private

	def wishlist_params
		params.require(:wishlist).permit(:title, :date, :description, :kind)
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/home/index.html.erb
<h1>Current Wishlists</h1>

<% @wishlists.each do |wish| %>
<div class='wishlist'>
	<h2>Wishlist Title: <%= wish.title %></h2>

</div>
<% end %>

<%= form_for @new_wishlist do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %>
  <%= f.label :type %>:<br>
    <%= f.radio_button(:kind, "christmas") %> Christmas <br />
    <%= f.radio_button(:kind, "birthday") %> Birthday <br />
    <%= f.radio_button(:kind, "other") %> Other <br />

  <%= f.submit %>
<% end %> 

app/views/items/edit.html.erb
<div data-role="page">
<div data-role="header collapsible" class="heading">
    <div id="headtitle" class="ui-btn-left">
    <%= @wishlist.title %>
    </div>
    <img id="icon" class ="ui-btn-right" src="<%= @pic %>">
</div>

<div id="listsubtitle">
wishlist type: <%= @wishlist.kind %><br>
<% if @belongstouser %>
  this is your list!
<% else %>
  by: <%= @wishlistowner.name %>
<% end %>
<p id="listdescrip"><%= @wishlist.description %></p>
</div>

<div id="spacer"></div>
<!-- list of existing items -->
<ul data-role="listview" class="items">
</ul>

<!-- Add new item will not show if it's not the user's list -->
<% if @belongstouser %>
<div class="forms">
</div>
<% end %>


<% if @user_id %>
<!-- if the user doesn't own the list then @user_id will exsist in that case we want to call Wishes.loadItems(wich initializes the page) with the user_id so we can have claim buttons -->
<script type="text/javascript">
  Wishes.loadItems(<%= @wishlist.id %>, <%= @user_id %>);
</script>

<% else %>

<script type="text/javascript">
  Wishes.loadItems(<%= @wishlist.id %>);
</script>

<% end %>

<% if @belongstouser %>
  <div id="spacer"></div>
<% end %>

<!-- slide menu panel -->
<div class="menu" id="menu">
<ul>
  <li><a href="#">View claimed items</a></li>
  <li><%= link_to "Log out", logout_path %></li>
</ul>
</div>


<div data-role="footer" data-position="fixed" data-tap-toggle="false">
    <div data-role="navbar">
      <ul>
        <li><a href="/wishlists" data-icon="bullets"> All Lists</a></li>
        <li><a href="/wishlists/new" data-icon="plus">New List</a></li>
        <li><a href="#" onclick="Gimme.showMenu()" class="morebutton" data-icon="star">More</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/items/user.html.erb
<div data-role="header collapsible" class="heading">
		<div id="headtitle" class="ui-btn-left">
		Wishes you've claimed
		</div>
		<img id="icon" class ="ui-btn-right" src="<%= @pic %>">
</div>


<div id="spacer"></div>
<!-- list of existing items -->
<ul data-role="listview" class="items">
</ul>

<script type="text/javascript">
  Wishes.loadUsersItems(<%= @user.id %>);
</script>

<!-- slide menu panel -->
<div class="menu" id="menu">
<ul>
  <li><%= link_to "View claimed items", claimed_items_path(@user.id) %></li>
  <li><%= link_to "Log out", logout_path %></li>
</ul>
</div>


<div data-role="footer" data-position="fixed" data-tap-toggle="false">
    <div data-role="navbar">
      <ul>
        <li><a href="/wishlists" data-icon="bullets"> All Lists</a></li>
        <li><a href="/wishlists/new" data-icon="plus">New List</a></li>
        <li><a href="#" onclick="Gimme.showMenu()" class="morebutton" data-icon="star">More</a></li>
      </ul>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gimme</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  
  <!-- Latest compiled and minified JavaScript -->
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all'%>

  <!-- viewport meta tag for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
<div class="" id="fix">

<%= yield %>

</div>

  <script src="https://rawgithub.com/arschmitz/jquery-mobile-datepicker-wrapper/master/jquery.mobile.datepicker.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  
</body>
</html>

app/views/partials/_birthday.html.erb
<style>

/*// Place all the styles related to the wishlists controller here.
// They will automatically be included in application.css.
// You can use Sass (SCSS) here: http://sass-lang.com/*/

/*COLORS
purple: #81479B
yellow:  #FCDC55
blue: #28AAE0
periwinkle: #BDC8E2 */


	textarea {
		font-color: #FEFEFE !important;
	}
	.ui-input-text {
		color: #324D5B !important;
	}
	textarea {
	}
	input {
	}
	#select-7-button, .ui-btn, .ui-btn a {
		background-color: #81479B !important;
		color: #BDC8E2 !important;
	}

#iconpic {
	background-image: url("http://i.imgur.com/smesVbW.png");
}
a:hover {
	color: #FCDC55 !important;
}
/*item title*/
.itemlisttitle {
}
/*list icon*/
.listpic {
}
.biglistpic {
}
.smlistpic {
}
/*list info*/
.listinfo {
}
#editbutton {
}
/*class of ul*/
.listinfo {
	color: #81479B !important;
}

#itemurl {
	color: #28AAE0;
}
.detailsbutton {
	background-color: #BDC8E2;
	color: #28AAE0 !important;
}

/*new item form*/
#newcontainer input{
}
#newwishbutton {
	background-color: #FCDC55 !important;
	color: #28AAE0 !important;
}

.listbuttons {
}

/*wishlist header css*/
#listsubtitle {
	color: #81479B;
}
#listdescrip {
	color: #FCDC55 !important;
}

#headtitle {
	font-size: 30px;
}

.claimed{
	background-color: rgba(255, 255, 255, .2) !important;
}

/*placeholder text*/
::-webkit-input-placeholder {
	color: #81479B !important;
	}
	:-moz-placeholder { /* Firefox 18- */
	   color: #81479B !important;
	}

	::-moz-placeholder {  /* Firefox 19+ */
	   color: #81479B !important;
	}

	:-ms-input-placeholder {  
	   color: #81479B !important;
	}

	/* entry text */
	.ui-link {
	}



</style>

app/views/partials/_christmas.html.erb
<style>

/*// Place all the styles related to the wishlists controller here.
// They will automatically be included in application.css.
// You can use Sass (SCSS) here: http://sass-lang.com/*/

/*COLORS
dark green: #001300
green:  #205936
light red: #B27B71
RED: #FF312A
maroon: #70250F 
bright green: #B27B71 */


	textarea {
		font-color: #FEFEFE !important;
	}
	.ui-input-text {
		color: #324D5B !important;
	}
	textarea {
	}
	input {
	}
	#select-7-button, .ui-btn, .ui-btn a {
		background-color: #FF5246 !important;
		color: white !important;
	}

	a:hover {
	color: #324D5B !important;
}

/*each li*/
.listitem {
}
/*item title*/
.itemlisttitle {
}
/*list icon*/
.listpic {
}
.biglistpic {
}
.smlistpic {
}
/*list info*/
.listinfo {
}

#iconpic {
	background-image: url("http://i.imgur.com/Hm7Udhe.png");
}

.detailsbutton {
	color: white;
	background-color: #B27B71;
	opacity: .7;
}
#editbutton {
}
/*class of ul*/
.listinfo {
	color: #70250F !important;
}

#itemurl {
	color: #B27B71;
}

/*new item form*/
#newcontainer input{
}
#newwishbutton {
	background-color: #84E376 !important;
	color: #70250F !important;
}

.listbuttons {
}

/*wishlist header css*/
#listsubtitle {
	color: #B27B71;
}
#listdescrip {
	color: #84E376 !important;
}

#headtitle {
	font-size: 30px;
}

.claimed{
	background-color: rgba(255, 255, 255, .2) !important;
}

/*placeholder text*/
::-webkit-input-placeholder {
	color: #FF312A !important;
	}
	:-moz-placeholder { /* Firefox 18- */
	   color: #FF312A !important;
	}

	::-moz-placeholder {  /* Firefox 19+ */
	   color: #FF312A !important;
	}

	:-ms-input-placeholder {  
	   color: #FF312A !important;
	}

	/* entry text */
	.ui-link {
	}



</style>

app/views/partials/_footer.html.erb
<div data-role="footer" data-position="fixed" data-tap-toggle="false">
    <div data-role="navbar">
      <ul>
        <li><a href="/wishlists" data-icon="bullets"> All Lists</a></li>
        <li><a href="/wishlists/new" data-icon="plus">New List</a></li>
        <li><a href="#" onclick="Gimme.showMenu()" class="morebutton" data-icon="star">More</a></li>
    </ul>
  </div>
</div>

app/views/partials/_slidemenu.html.erb
 <!-- slide menu panel -->
<div class="menu" id="menu">
<ul>
  <li><%= link_to "View claimed items", claimed_items_path(@user_id) %></li>
  <li><%= link_to "Log out", logout_path %></li>
</ul>
</div>

app/views/partials/_wedding.html.erb
<style>

/*// Place all the styles related to the wishlists controller here.
// They will automatically be included in application.css.
// You can use Sass (SCSS) here: http://sass-lang.com/*/

/*COLORS
purple: #81479B
yellow:  #FCDC55
blue: #443C31
periwinkle: #BDC8E2 */

/*Muted blue: #A1B2B4
Lighter blue: #B2C3C6
Black-brown: #443C31
Lighter black-brown: #66635a
Grey: #7F8179*/


	textarea {
		font-color: #443C31 !important;
	}
	.ui-input-text {
		color: #A1B2B4 !important;
	}
	textarea {
	}
	input {
	}
	#select-7-button, .ui-btn, .ui-btn a {
		background-color: #66635a !important;
		color: #B2C3C6 !important;
	}

#iconpic {
	background-image: url("http://i.imgur.com/hOcjNGe.png");
}

/*each li*/
.listitem {
}
/*item title*/
.itemlisttitle {
}
/*list icon*/
.listpic {
}
.biglistpic {
}
.smlistpic {
}
/*list info*/
.listinfo {
}
#editbutton {
}
/*class of ul*/
.listinfo {
	color: #7F8179 !important;
}

#itemurl {
	color: #443C31;
}
.detailsbutton {
	background-color: rgba(255, 255, 255, .8);
	color: #443C31 !important;
}

/*new item form*/
#newcontainer input{
}
#newwishbutton {
	background-color: #B2C3C6 !important;
	color: #443C31 !important;
}

.listbuttons {
}

/*wishlist header css*/
#listsubtitle {
	color: #66635a;
}
#listdescrip {
	color: #A1B2B4 !important;
}

#headtitle {
	font-size: 30px;
	color: #7F8179;
}

.claimed{
	background-color: rgba(0, 0, 0, .2) !important;
}

/*placeholder text*/
::-webkit-input-placeholder {
	color: #7F8179 !important;
	}
	:-moz-placeholder { /* Firefox 18- */
	   color: #7F8179 !important;
	}

	::-moz-placeholder {  /* Firefox 19+ */
	   color: #7F8179 !important;
	}

	:-ms-input-placeholder {  
	   color: #7F8179 !important;
	}

	/* entry text */
	.ui-link {
	}



</style>

app/views/wishlists/edit.html.erb
<div data-role="page">

  <div data-role="header collapsible" class="heading">
    <div id="headtitle" class="ui-btn-left">
        Edit 
    </div>
    <img id="icon" class ="ui-btn-right" src="<%= @pic %>">
  </div>
  <!-- closes header div -->


<%= form_for @wishlist, method: "PUT"  do |f| %>
      <%= f.text_field :title, :class => 'newfield', :placeholder => "wishlist name" %>
    

    <%= f.text_area :description, :class => 'newfield', :placeholder => "add a description (optional)" %>

<div class="ui-field-contain" id="choosetheme">
  <select name="wishlist[kind]">
    <option>choose a theme</option>
    <option value="christmas">Christmas</option>
    <option value="birthday">Birthday</option>
    <option value="wedding">Wedding</option>
    <option value="other">Other</option>
  </select>
</div>
  <!-- closes controlgroup fieldset -->

  <%= f.text_field :date, id: "datepicker", :class => 'newfield', :placeholder => "event date"%>

  <button data-icon="carat-r" data-iconpos="right">
    <%= f.submit 'save & return to view all', :class => 'submitbutton' %>
    </button>
  <br>
<% end %>
<!-- closes form -->

<!-- slider menu -->
<%= render "partials/slidemenu" %>

<!-- footer -->
<%= render "partials/footer" %>

</div>
<!-- closes data-role div -->

app/views/wishlists/index.html.erb
<div data-role="header collapsible" class="heading">
    <div id="headtitle" class="ui-btn-left">
    All wishlists
    </div>
</div>

<!-- LIST ALL WISHLISTS -->
<% @wishlists.each do |wish| %>

<!-- IF [wish] BELONGS TO USER -->
<!-- make title and hidden buttons -->
  <% if (wish.user_id === @user_id) %>
    <div class='wishlistslist' data-role="content">
      <ul data-role="listview" data-icon="carat-d" data-iconpos="right">
        <li>
          <a href="#" class="titlebutton"> <%= wish.title %> </a>
        </li>
    <!-- hidden buttons -->
        <div class="listbuttons hide">
          <div data-tap-toggle="false">
            <div data-role="navbar">
              <ul>
                <li><a href="<%= wishlist_path(wish.id)%>" data-icon="eye">View</a></li>
                <li><a href="<%= edit_wishlist_path(wish.id)%>" data-icon="edit">Edit</a></li>
                <li>
                  <%= form_for wish, method: "DELETE"  do |f| %>
                    <%= button_tag("Delete", data: { "icon" => "delete" }) %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>    <!-- end -->
        </div>
    <!-- close hidden buttons -->
      </ul>
    </div>

  <!-- IF [wish] IS NOT BY THE USER -->
  <!-- make only the header and link directly to the list -->
  <% else %>
    <div class='wishlistslist' data-role="content">
      <ul data-role="listview" data-icon="arrow-r" data-iconpos="right">
        <li>
          <a href="<%= wishlist_path(wish.id)%>" class="titlebutton"> <%= wish.title %> <span class="by"> by <%= wish.user.name %></span></a>
        </li>
      </ul>
    </div>
  <% end %>
  <br>
<% end %>
<!-- end listing loop -->

<!-- slider menu -->
<%= render "partials/slidemenu" %>

<!-- footer -->
<%= render "partials/footer" %>

<script>
var open;
//SHOW BUTTONS FUNCTION
  $(document).on("click", ".wishlistslist", function() {
    var dis = $(this).find('.listbuttons');
    dis.removeClass('hide');
    var icon = $(this).find('');
    if (dis.height() === 0) {
      if (open) {
        open.animate({'height': '0px'}, 150);
      }
      dis.animate({'height': dis.get(0).scrollHeight}, 150);   
    } else {
      dis.animate({'height': '0px'}, 150, function() {
        dis.addClass('hide');
      });
    }
    open = dis;
  });
</script>

app/views/wishlists/new.html.erb
<div data-role="page">

	<div data-role="header collapsible" class="heading">
		<div id="headtitle" class="ui-btn-left">
		New wishlist
		</div>
		<img id="icon" class ="ui-btn-right" src="<%= @pic %>">
	</div>
	<!-- closes header div -->

<%= form_for @wishlist do |f| %>
	  	<%= f.text_field :title, :class => 'newfield', :placeholder => "wishlist name", :maxlength => "25" %>
	  

		<%= f.text_area :description, :class => 'newfield', :placeholder => "add a description (optional)" %>


<!-- <fieldset data-role="controlgroup">
	<input type="radio" id="christmas" name="kind" value="christmas"> 
		<label for="christmas"> Christmas</label><br>
	<input type="radio" id="birthday" name="kind" value="birthday"> 
		<label for="birthday"> birthday</label><br>
	<input type="radio" id="other" name="kind" value="other"> 
		<label for="other"> other</label><br>
</fieldset> -->

<div class="ui-field-contain" id="choosetheme">
  <!-- <label for="select-choice-1" class="select">Choose a theme:</label> -->
  <select name="wishlist[kind]">
  	<option>choose a theme</option>
    <option value="christmas">Christmas</option>
    <option value="birthday">Birthday</option>
    <option value="wedding">Wedding</option>
    <option value="other">Other</option>
  </select>
</div>

	<!-- closes controlgroup fieldset -->

	<%= f.text_field :date, :placeholder => "event date", data: { "role" => "date" } %>

	<button data-icon="carat-r" data-iconpos="right">
	  <%= f.submit 'create & add items ', :class => 'submitbutton' %>
	  </button>
	<br>
<% end %>

<!-- closes form -->

<!-- slider menu -->
<%= render "partials/slidemenu" %>

<!-- footer -->
<%= render "partials/footer" %>




<!-- closes data-role div -->

app/views/wishlists/show.html.erb
<div data-role="page">
<div data-role="header collapsible" class="heading">
		<div id="headtitle" class="ui-btn-left">
		<%= @wishlist.title %>
		</div>
</div>

<div id="iconpic"></div>

<div id="listsubtitle">
<% if @belongstouser %>
	by you!
<% else %>
	<%= @wishlist.kind %> wishlist by <%= @wishlistowner.name %>
<% end %>
<p id="listdescrip"><%= @wishlist.description %></p>
</div>

<div id="spacer"></div>
<!-- list of existing items -->
<ul data-role="listview" class="items">
</ul>

<!-- Add new item will not show if it's not the user's list -->
<% if @belongstouser %>
<div class="forms">
</div>
<% end %>

<% if @nn_user_id %>
<!-- if the user doesn't own the list then @nn_user_id will exsist in that case we want to call Wishes.loadItems(wich initializes the page) with the nn_user_id so we can have claim buttons -->
<script type="text/javascript">
  Wishes.loadItems(<%= @wishlist.id %>, "<%= @wishlist.kind %>", <%= @nn_user_id %>);
</script>

<% else %>
<script type="text/javascript">

  Handlebars.registerHelper('escape', function(variable) {
    return variable.replace(/(['"])/g, '\\$1');
  });
  Wishes.loadItems(<%= @wishlist.id %>, "<%= @wishlist.kind %>");

</script>

<% end %>

<% if @belongstouser %>
  <div id="spacer"></div>
<% end %>




<!-- slide menu panel -->
<div class="menu" id="menu">
<ul>
  <li><%= link_to "View claimed items", claimed_items_path(@user_id) %></li>
  <li><%= link_to "Log out", logout_path %></li>
</ul>
</div>


<div data-role="footer" data-position="fixed" data-tap-toggle="false">
    <div data-role="navbar">
      <ul>
        <li><a href="/wishlists" data-icon="bullets"> All Lists</a></li>
        <li><a href="/wishlists/new" data-icon="plus">New List</a></li>
        <li><a href="#" onclick="Gimme.showMenu()" class="morebutton" data-icon="star">More</a></li>
      </ul>
    </div>
  </div>
</div>

<!-- rendering appropriate CSS -->
<% if (@wishlist.kind === "christmas") %>
  <%= render "partials/christmas" %>
<% elsif (@wishlist.kind === "birthday") %>
  <%= render "partials/birthday" %>
<% elsif (@wishlist.kind === "wedding") %>
  <%= render "partials/wedding" %>
<% end %>

<script>


$(document).on("click", ".wishlistslist", function() {
    var dis = $(this).find('.listbuttons');
    dis.removeClass('hide');
    var icon = $(this).find('');
    if (dis.height() === 0) {
      if (open) {
        open.animate({'height': '0px'}, 150);
      }
      dis.animate({'height': dis.get(0).scrollHeight}, 150);   
    } else {
      dis.animate({'height': '0px'}, 150, function() {
        dis.addClass('hide');
      });
    }
    open = dis;
  });

//ACCORDION FUNCTION
$(document).on("click", ".listitem", function() {

  var dis = $(this).find('.listinfo');
  var dispic = $(this).find('.listpic');
//add hide class to all other descriptions

  if (dis.hasClass('hide')) {

    $('.listinfo').each(function() {
      $(this).addClass('hide');
    });
    $('.listpic').each(function() {
      $(this).addClass('smlistpic');
    });
    $('.listitem').each(function() {
      $(this).css('height', '65px');
    });

    dispic.removeClass('smlistpic');
    dispic.addClass('biglistpic');
    dis.removeClass('hide');
    $(this).css('height', 'auto');
    if ($(this).height() < 115) {
      $(this).css('height', '115px');
    }
  } else {
    dispic.addClass('smlistpic');
    dispic.removeClass('biglistpic');
    dis.addClass('hide');
    $(this).css('height', '65px');
  }

});

</script>